steps:
- name: 'gcr.io/cloud-builders/java/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/spinnaker-demo:meeseks', '.']
images: ['gcr.io/$PROJECT_ID/spinnaker-demo:meeseks']
